name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Iinstall requirements
      run: python -m pip install build --user
    - name: Build
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
